---
- name: Dev |  Get dependencies in repository
  command: "mix deps.get"
  args:
    chdir: "{{ git_clone_path }}/{{ item.value.name | basename }}"
  with_dict: "phoenix_repos"
  become: yes
  become_user: "{{ phoenix_user }}"
  ignore_errors: yes ## These commands should be handled different to avoid possible errors..

- name: Dev | Create dev database
  shell: " mix local.rebar --force && mix ecto.create --force"
  args:
    chdir: "{{ git_clone_path }}/{{ item.value.name | basename }}"
  with_dict: "phoenix_repos"
  become: yes
  become_user: "{{ phoenix_user }}"
  ignore_errors: yes ## These commands should be handled different to avoid possible errors..

- name: Dev | Migrate dev database
  shell: "mix ecto.migrate --force"
  args:
    chdir: "{{ git_clone_path }}/{{ item.value.name | basename }}"
  with_dict: "phoenix_repos"
  become: yes
  become_user: "{{ phoenix_user }}"
  ignore_errors: yes ## These commands should be handled different to avoid possible errors..

- name: Dev | Run phoenix service
  shell: "nohup mix phoenix.server >> /tmp/phoenix_server.log 2>&1&"
  args:
    chdir: "{{ git_clone_path }}/{{ item.value.name | basename }}"
  with_dict: "phoenix_repos"
  become: yes
  become_user: "{{ phoenix_user }}"
  ignore_errors: yes ## These commands should be handled different to avoid possible errors.
