---
- group:
    name="{{ phoenix_group }}"
    state=present
- user:
    name="{{ phoenix_user }}"
    comment="Created by Ansible"
    group="{{ phoenix_group }}"
    groups="{{ phoenix_groups }}"
    state=present

- apt:
    deb=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

- apt:
    name="{{ item }}"
    update_cache=yes
    state=present
  with_items:
    - "esl-erlang={{ esl_erlang_version }}"
    - "elixir={{ elixir_version }}"
    - "inotify-tools"

- command: mix local.hex --force
  become: yes
  become_user: "{{ phoenix_user }}"
  
- command: mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force
  become: yes
  become_user: "{{ phoenix_user }}"
